name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🔧 Refactoring'
    label: 'Refactoring'
  - title: '📖 Documentation'
    label: 'documentation'
  - title: '🛠 Other Changes'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: enhancement
    branch:
      - '/feature\/.+/'
  - label: bug
    branch:
      - '/fix\/.+/'
  - label: Refactoring
    branch:
      - '/refactor\/.+/'
  - label: documentation
    branch:
      - '/doc\/.+/'