name: Create Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  # push:
  #   tags:
  #     - '*'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Tag
        run: |
          TAG_NAME=${{ github.head_ref }}  # Extract 'release/vx.x.x' branch name
          TAG_NAME=${TAG_NAME#release/v}   # Remove 'release/v' prefix
          git tag $TAG_NAME
          git push origin $TAG_NAME

  # create-release:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Extract tag name
  #       id: get_tag
  #       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
  #     - name: Create Release Notes
  #       uses: github/release-notes-preview-action@v1
  #       id: release
  #       with:
  #         config_path: .github/release.yml
  #         draft: true
  #         name: ${{ env.RELEASE_VERSION }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Create Release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: ${{ steps.release.outputs.body }}
  #         draft: false
  #         prerelease: true
